[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "dist"
  NODE_ENV = "production"

[dev]
  publish="dist"
  port = 7998
  NODE_ENV = "development"

# [dev.environment]
  # secretKey= "dsjfsdjfgdjhfgdjhgfdjhdfgjhdfj"
  # USER_NAME = "postgres"
  # PASSWORD = "root"
  # DB = "beatbuzz-user-service"
  # HOST = "localhost"
  # DB_PORT = 5432
