name: Docker Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t beatbuzz-user-service .
          docker tag beatbuzz-user-service your-digitalocean-registry/beatbuzz-user-service
          docker push your-digitalocean-registry/beatbuzz-user-service

      - name: Deploy to DigitalOcean Droplet
        run: |
          ssh root@139.59.89.111 'docker pull your-digitalocean-registry/beatbuzz-user-service && docker-compose up -d'
